swagger: "2.0"
info:
  description: "The description of API of NextDoor Farm HSE ASD Project"
  version: "1.0.0"
  title: "Swagger NextDoor Farm"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "nextdoorfarm.notion.site"
basePath: "/v1"
tags:
  - name: "Customers"
    description: "Customer CRUD operations"
schemes:
  - "https"
  - "http"
paths:
# TODO

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
